// 화면 문구 모음. 버튼·상태 이름은 여기에서만 정의해 화면 간 표현을 맞춘다.
// (humanize-korean 검토 대상. 코드 식별자·값은 바꾸지 않는다.)
import type {
  AssessmentKind,
  AssessmentStatus,
  ConsultStatus,
  FixedCondition,
  GroupType,
  Mode,
  TimeBand,
} from '../lib/types';

export const T = {
  common: {
    loading: '불러오는 중입니다…',
    retry: '다시 시도',
    save: '저장',
    saving: '저장 중…',
    saved: '저장했습니다.',
    cancel: '취소',
    close: '닫기',
    edit: '수정',
    delete: '삭제',
    back: '이전',
    next: '다음',
    copy: '복사',
    copied: '복사했습니다.',
    none: '없음',
    optional: '선택',
    required: '필수',
    unknown: '모름',
    undecided: '미정',
    networkError: '인터넷 연결을 확인한 뒤 다시 시도해주세요.',
    serverError: '요청을 처리하지 못했습니다. 잠시 후 다시 시도해주세요.',
  },

  setup: {
    title: '서버 연결 설정이 필요합니다',
    body: 'Supabase 주소와 공개 키가 설정되지 않아 응답을 저장할 수 없습니다. 관리자는 배포 설정(README의 ‘최소 설정’)을 확인해주세요.',
  },

  home: {
    title: '수업 준비실',
    body: '학습 상담은 선생님이 보내드린 링크로 작성할 수 있습니다. 받으신 문자나 메시지의 링크를 다시 눌러주세요.',
    admin: '선생님 로그인',
    notFoundTitle: '페이지를 찾을 수 없습니다',
    notFoundBody: '주소를 다시 확인해주세요. 상담 링크라면 받으신 문자의 링크를 다시 눌러주세요.',
  },

  devBanner: '개발용 로컬 DB로 실행 중입니다. 이 브라우저 안에만 저장되며 실제 서버에는 저장되지 않습니다.',

  // ---------------------------------------------------------------------------
  // 학부모 화면
  // ---------------------------------------------------------------------------
  parent: {
    headerWithTeacher: (name: string) => `${name} 선생님 | 학습 상담`,
    headerDefault: '학습 상담',
    defaultEyebrow: '학생에게 맞는 수업을 준비하는 첫 단계',
    defaultTitle: '학생의 학습 상황에 맞춰 수업을 준비합니다.',
    defaultBody:
      '학교 진도와 공부할 때 어려운 부분, 수업에서 바라는 점을 알려주세요. 첫 수업에서 이해도를 확인한 뒤 교재와 학습 계획을 조정하겠습니다.',
    defaultNote: '아시는 범위에서 답해주세요. 아직 확인하지 못한 내용은 상담하면서 함께 정리합니다.',
    start: '학습 상담 작성하기',
    estimate: (min: number) => `작성 시간은 ${min}분 정도입니다.`,
    processTitle: '수업은 이렇게 준비합니다',
    process: [
      { title: '학습 상황 확인', body: '학교 진도와 교재, 지금까지의 학습 경험과 목표를 확인합니다.' },
      { title: '이해도 진단', body: '첫 수업에서 문제를 푸는 모습을 보며 어떻게 접근하는지, 어느 개념에서 막히는지, 어떤 실수를 반복하는지 확인합니다.' },
      { title: '수업 계획 조정', body: '첫 수업에서 확인한 내용에 맞춰 교재와 진도, 숙제 분량을 정합니다.' },
    ],
    coursesTitle: '상담할 수업',
    coursesTitleMulti: '선택할 수 있는 수업',
    perspective: '지도 방식',
    teacherTitle: (name: string) => (name ? `${name} 선생님` : '선생님 소개'),
    policyTitle: '수업료·환불 안내',
    siblingNote: '한 번에 학생 한 명의 내용을 작성합니다. 형제자매는 각각 작성해주세요.',
    photoNote: '시험지 사진은 과목별 학습 정보 단계에서 올릴 수 있습니다. 교과서 사진이 필요하면 상담하면서 따로 부탁드리겠습니다.',
    photos: {
      add: '사진 선택',
      uploading: '올리는 중',
      done: '올림',
      failedShort: '실패',
      uploaded: (name: string) => `${name} 사진을 올렸습니다.`,
      failed: (name: string) => `${name} 사진을 올리지 못했습니다. ‘다시 시도’를 눌러주세요.`,
      limit: (n: number) => `사진은 최대 ${n}장까지 올릴 수 있어 일부만 올렸습니다.`,
      count: (n: number, max: number) => `${n}장 / 최대 ${max}장 · 사진은 선생님만 볼 수 있습니다.`,
      alt: (n: number) => `올린 사진 ${n}`,
      removeLabel: (n: number) => `올린 사진 ${n} 빼기`,
      previewOnly: '미리보기에서는 사진을 올릴 수 없습니다.',
      waiting: '사진을 올리는 중입니다. 다 올라간 뒤 다시 눌러주세요.',
    },

    status: {
      invalid: { title: '링크를 확인할 수 없습니다', body: '주소가 정확한지 확인해주세요. 받으신 링크를 다시 눌러도 열리지 않으면 선생님께 새 링크를 요청해주세요.' },
      closed: { title: '지금은 접수하지 않습니다', body: '이 링크의 수업 상담 접수가 마감되었습니다. 상담이 필요하시면 선생님께 직접 연락해주세요.' },
      expired: { title: '접수 기간이 지났습니다', body: '이 링크의 접수 기간이 끝났습니다. 상담이 필요하시면 선생님께 새 링크를 요청해주세요.' },
      full: { title: '접수 인원이 찼습니다', body: '이 링크로 받을 수 있는 상담이 모두 접수되었습니다. 선생님께 직접 연락해주세요.' },
      not_ready: { title: '아직 접수를 준비하고 있습니다', body: '상담 접수를 시작하기 전입니다. 잠시 후 다시 열어주세요.' },
      loadError: { title: '상담 양식을 불러오지 못했습니다', body: '인터넷 연결을 확인한 뒤 다시 시도해주세요.' },
    },

    steps: {
      basic: '기본 정보',
      schedule: '수업 선택·일정',
      scheduleSingle: '수업 일정',
      course: (subject: string) => `${subject} 학습 정보`,
      review: '검토·동의',
    },
    stepOf: (n: number, total: number) => `${total}단계 중 ${n}단계`,
    leaveWarning: '작성 중인 내용이 저장되지 않습니다. 페이지를 떠나시겠어요?',
    backToReview: '검토 화면으로',
    errorSummary: (n: number) => `확인이 필요한 항목이 ${n}개 있습니다.`,
    goToError: '해당 항목으로 이동',

    basic: {
      intro: '수업 준비와 연락에 필요한 정보만 받습니다.',
      parentName: '학부모 성함',
      parentPhone: '연락 가능한 휴대전화 번호',
      parentPhoneHelp: '하이픈(-) 없이 입력하셔도 됩니다.',
      studentName: '학생 이름',
      studentNameHelp: '별칭이나 성을 뺀 이름도 괜찮습니다. 선생님이 알아볼 수 있게만 적어주세요.',
      grade: '학교급·학년',
      gradePlaceholder: '선택해주세요',
      gradeOther: '기타',
      gradeNote: '학년 정보',
      gradeNoteHelp: '예: 검정고시 준비, 홈스쿨링',
      schoolName: '학교 이름',
      generalRequest: '전반적으로 바라시는 점',
      generalRequestHelp: '수업 전체에 대해 미리 알려주실 내용이 있으면 적어주세요.',
      extraTitle: '학생에 대해',
    },

    schedule: {
      chooseTitle: '상담할 수업을 골라주세요',
      chooseHelp: '여러 수업을 함께 고를 수 있습니다. 기본 정보는 한 번만 받고 학습 정보와 일정은 수업마다 따로 여쭙니다.',
      chooseError: '수업을 하나 이상 골라주세요.',
      fixedTitle: '정해진 조건',
      askTitle: '희망 조건',
      wishNote: '여기서 고르신 시간은 예약 확정이 아니라 희망 조건입니다. 상담하면서 최종 일정을 정합니다.',
      startDate: '첫 수업 희망 날짜',
      startUndecided: '아직 정하지 않았어요',
      slots: '가능한 요일과 시작 시각',
      slotsHelp: (minutes: number | null) =>
        minutes ? `수업은 회당 ${minutes}분입니다. 시작 시각을 고르면 끝나는 시각을 함께 보여드립니다.` : '가능한 요일과 시작 시각을 모두 추가해주세요.',
      addSlot: '시간 추가',
      removeSlot: (label: string) => `${label} 삭제`,
      weekday: '요일',
      startTime: '시작 시각',
      endsAt: (t: string) => `${t} 종료`,
      timeUndecided: '시간은 상담하면서 정하고 싶어요',
      duration: '희망 수업 기간',
      durationOptions: ['우선 4회', '우선 8회', '한 학기', '이번 시험까지', '꾸준히 진행'],
      sessions: '주당 수업 횟수',
      sessionsOption: (n: number) => `주 ${n}회`,
      minutes: '회당 수업 시간',
      minutesOption: (n: number) => `${n}분`,
      noPreference: '선생님과 상의할게요',
      mode: '수업 방식',
      groupType: '수업 형태',
      note: '일정 관련 요청사항',
      noteHelp: '예: 화요일은 학원이 있어 8시 이후만 가능해요.',
      copyTitle: '다른 수업에 같은 시간 적용',
      copyButton: (subject: string) => `${subject} 수업에도 같은 시간 적용`,
      copyPreviewTitle: '적용하기 전에 확인해주세요',
      copyBefore: '지금',
      copyAfter: '적용 후',
      copyApply: '적용하기',
      copySkipped: (n: number) => `이 수업에서 고를 수 없는 시간 ${n}개는 빼고 적용합니다.`,
      consecutive: '여러 수업을 같은 날 이어서 받고 싶으신가요?',
      consecutiveOptions: { yes: '이어서 받고 싶어요', no: '다른 날로 나누고 싶어요', either: '상관없어요' },
      consecutiveNote: '이어서 받는 수업에 대한 요청',
    },

    course: {
      perspectiveTitle: '이 과목은 이렇게 살펴봅니다',
      learningTitle: '학습 상황',
      examTitle: '학교 시험과 평가',
      examHelp: '아시는 범위에서 적어주세요. 이미 치른 시험은 ‘이미 끝남’, 정해지지 않은 일정은 ‘미정’, 해당하지 않는 평가는 ‘해당 없음’을 골라주세요.',
      examStatus: '입력 방식',
      examPeriod: '시험 기간',
      examPeriodStart: '시작일',
      examPeriodEnd: '종료일',
      examDate: '이 과목 시험일',
      examScope: '시험 범위',
      addAssessment: '평가 추가',
      removeAssessment: (name: string) => `${name} 삭제`,
      assessmentName: '평가 이름',
      copyExamPeriod: (subject: string) => `${subject}에 입력한 시험 기간 가져오기`,
      copyExamPeriodDone: '시험 기간을 가져왔습니다. 과목별 시험일과 범위는 따로 확인해주세요.',
      homework: '이 과목 숙제에 쓸 수 있는 시간',
      homeworkHelp: '학교 숙제나 다른 학원 숙제는 빼고 이 수업 숙제에 쓸 수 있는 시간을 골라주세요.',
      homeworkTotal: (text: string) => `선택한 수업 전체: ${text}`,
    },

    review: {
      intro: '보내기 전에 내용을 확인해주세요. 고칠 부분이 있으면 각 영역의 ‘수정’을 눌러주세요.',
      common: '기본 정보',
      schedule: '수업별 일정',
      learning: '과목별 학습 정보',
      exams: '시험·숙제',
      requests: '추가 요청사항',
      notAnswered: '답하지 않음',
      privacyTitle: '개인정보 수집·이용 안내',
      privacyItems: '수집 항목',
      privacyItemsText:
        '학부모 성함, 휴대전화 번호, 학생 이름(또는 별칭), 학교급·학년, 학교 이름(선택), 수업 희망 일정, 학습 상황과 시험 정보, 시험지 사진(선택), 요청사항',
      privacyPurpose: '이용 목적',
      privacyRetention: '보관 기간',
      privacyDeletion: '삭제 요청 방법',
      privacyOperator: '운영자',
      privacyContact: '연락처',
      privacyRefuse: '동의하지 않으셔도 됩니다. 다만 이 경우에는 이 양식으로 상담을 접수할 수 없어 선생님께 직접 연락해주셔야 합니다.',
      consent: '위 안내를 읽고 개인정보 수집·이용에 동의합니다.',
      consentError: '개인정보 수집·이용에 동의해주셔야 접수할 수 있습니다.',
      submit: '상담 내용 보내기',
      submitting: '보내는 중입니다…',
    },

    submitErrors: {
      network: '보내지 못했습니다. 인터넷 연결을 확인한 뒤 ‘상담 내용 보내기’를 다시 눌러주세요. 작성하신 내용은 그대로 남아 있습니다.',
      server: '보내지 못했습니다. 잠시 후 다시 눌러주세요. 작성하신 내용은 그대로 남아 있습니다.',
      validation: '확인이 필요한 항목이 있습니다. 표시된 항목을 고친 뒤 다시 보내주세요.',
      rateLimited: '짧은 시간에 요청이 많아 잠시 접수를 멈췄습니다. 몇 분 뒤 다시 보내주세요.',
      formOutdated:
        '그사이 상담 양식이 바뀌어 지금 내용으로는 보낼 수 없습니다. 작성하신 내용을 따로 적어두신 뒤 페이지를 새로고침해주세요.',
      closed: '그사이 접수가 마감되었습니다. 상담이 필요하시면 선생님께 따로 연락 부탁드립니다.',
      courseUnavailable: '선택하신 수업 중 접수가 끝난 수업이 있습니다. 페이지를 새로고침해 수업을 다시 골라주세요.',
    },

    done: {
      title: '접수되었습니다',
      defaultMessage:
        '상담 내용이 접수되었습니다. 보내주신 내용을 확인한 뒤 수업 일정과 준비 사항을 안내드리겠습니다. 아직 확인하지 못한 내용은 상담하면서 함께 정리하겠습니다.',
      receipt: '접수 번호',
      receiptHelp: '문의하실 때 접수 번호를 알려주시면 빠르게 찾을 수 있습니다.',
      closeHint: '이 창은 닫으셔도 됩니다.',
    },
  },

  // ---------------------------------------------------------------------------
  // 입력 오류 (코드 → 문구)
  // ---------------------------------------------------------------------------
  errors: {
    required: '이 항목에 답해주세요.',
    requiredWithUnknown: (label: string) => `이 항목에 답해주세요. 답하기 어려우면 ‘${label}’에 표시해주세요.`,
    requiredChoice: '하나 이상 골라주세요.',
    parentNameRequired: '학부모 성함을 입력해주세요.',
    parentPhoneRequired: '연락받으실 휴대전화 번호를 입력해주세요.',
    studentNameRequired: '학생 이름이나 별칭을 입력해주세요.',
    gradeNoteRequired: '학년 정보를 적어주세요.',
    assessmentNameRequired: '평가 이름을 적어주세요.',
    too_long: (max: number) => `${max}자 이내로 적어주세요.`,
    invalid: '형식을 확인해주세요.',
    invalid_phone: '휴대전화 번호를 확인해주세요. 예: 010-1234-5678',
    invalid_option: '선택지를 다시 골라주세요.',
    exclusive_option: '‘잘 모르겠음’은 다른 항목과 함께 고를 수 없습니다.',
    out_of_range: '입력할 수 있는 범위를 벗어났습니다.',
    too_many: '사진은 최대 5장까지 올릴 수 있습니다.',
    conflict_undecided: '‘미정’과 구체적인 값을 함께 고를 수 없습니다.',
    startDateRequired: '희망 날짜를 고르거나 ‘아직 정하지 않았어요’를 선택해주세요.',
    startDateRange: '오늘부터 1년 안의 날짜를 골라주세요.',
    slotsRequired: '가능한 시간을 하나 이상 추가하거나 ‘상담하면서 정하고 싶어요’를 선택해주세요.',
    slotIncomplete: '요일과 시작 시각을 모두 골라주세요.',
    slotDuplicate: '같은 요일·시각이 두 번 들어가 있습니다.',
    slotNotOffered: '이 수업에서 고를 수 없는 시간입니다.',
    gradeRequired: '학교급과 학년을 골라주세요.',
    homeworkRequired: '숙제에 쓸 수 있는 시간을 골라주세요. 아직 정하기 어려우면 ‘상담 후 결정’을 선택하시면 됩니다.',
    assessmentStatus: '입력 방식을 골라주세요.',
    assessmentEmpty: '시험 기간, 시험일, 범위 중 하나 이상 적거나 ‘모름’·‘미정’을 골라주세요.',
    beforeStart: '종료일이 시작일보다 앞설 수 없습니다.',
    conflict_status: '‘이미 끝남’·‘모름’·‘미정’·‘해당 없음’을 고르면 날짜와 범위는 비워주세요.',
  },

  // ---------------------------------------------------------------------------
  // 공통 라벨
  // ---------------------------------------------------------------------------
  labels: {
    schoolLevel: { elementary: '초등학교', middle: '중학교', high: '고등학교', any: '학교급 무관', other: '기타' } as Record<string, string>,
    schoolShort: { elementary: '초', middle: '중', high: '고' } as Record<string, string>,
    mode: { in_person: '대면', online: '화상', hybrid: '화상·대면 혼합', negotiable: '협의', any: '상관없음' } as Record<Mode | 'any', string>,
    groupType: { individual: '개인', group: '그룹', negotiable: '협의', any: '상관없음' } as Record<GroupType | 'any', string>,
    timeBand: { morning: '오전', afternoon: '오후', evening: '저녁' } as Record<TimeBand, string>,
    fixedCondition: {
      weekdays: '요일',
      start_time: '시작 시각',
      minutes: '회당 시간',
      sessions: '주당 횟수',
      start_date: '시작일',
      duration: '수업 기간',
    } as Record<FixedCondition, string>,
    assessmentKind: {
      midterm: '중간고사',
      final: '기말고사',
      performance: '수행평가',
      unit: '단원평가',
      other: '기타 평가',
    } as Record<AssessmentKind, string>,
    assessmentStatus: {
      entered: '입력',
      finished: '이미 끝남',
      unknown: '모름',
      undecided: '미정',
      not_applicable: '해당 없음',
    } as Record<AssessmentStatus, string>,
    consultStatus: {
      new: '신규 접수',
      reviewing: '검토 중',
      needs_info: '추가 확인 필요',
      scheduled: '일정 확정',
      on_hold: '보류',
    } as Record<ConsultStatus, string>,
    consecutive: { yes: '이어서 받고 싶음', no: '다른 날로 나누고 싶음', either: '상관없음' } as Record<string, string>,
  },

  course: {
    target: '대상',
    scope: '지도 범위',
    mode: '수업 방식',
    groupType: '수업 형태',
    weekly: '주당 횟수',
    minutes: '회당 시간',
    days: '요일',
    time: '시간',
    startDate: '시작일',
    duration: '수업 기간',
    negotiable: '협의',
    adjustable: '조율 가능',
    toDiscuss: '상담하며 정할 조건',
    fixed: '확정',
    weeklyValue: (n: number) => `주 ${n}회`,
    minutesValue: (n: number) => `${n}분`,
  },

  // ---------------------------------------------------------------------------
  // 관리자 화면
  // ---------------------------------------------------------------------------
  admin: {
    nav: {
      dashboard: '대시보드',
      responses: '응답·상담',
      courses: '수업 관리',
      forms: '과목·설문 관리',
      settings: '운영 설정',
    },
    signOut: '로그아웃',
    login: {
      title: '관리자 로그인',
      email: '이메일',
      password: '비밀번호',
      submit: '로그인',
      submitting: '확인 중…',
      failed: '이메일 또는 비밀번호가 맞지 않습니다.',
      notAdmin: '로그인은 되었지만 관리자 권한이 없는 계정입니다. 관리자 등록이 필요하면 README의 ‘관리자 계정 등록’을 확인해주세요.',
      forgot: '비밀번호를 잊으셨나요?',
      expired: '로그인 시간이 지나 다시 로그인이 필요합니다.',
    },
    reset: {
      requestTitle: '비밀번호 재설정',
      requestHelp: '관리자 이메일을 입력하면 재설정 링크를 보내드립니다. 등록되지 않은 이메일이어도 같은 안내가 표시됩니다.',
      requestSubmit: '재설정 링크 받기',
      requestSent: '입력하신 주소가 관리자 계정이면 재설정 링크가 발송됩니다. 메일함을 확인해주세요.',
      verifyTitle: '새 비밀번호 설정',
      verifyHelp: '아래 버튼을 눌러 재설정 링크를 확인한 뒤 새 비밀번호를 입력해주세요.',
      verifyButton: '재설정 링크 확인',
      verifyFailed: '링크가 만료되었거나 이미 사용되었습니다. 재설정 링크를 다시 받아주세요.',
      newPassword: '새 비밀번호',
      newPasswordHelp: '8자 이상으로 입력해주세요.',
      confirmPassword: '새 비밀번호 확인',
      mismatch: '두 비밀번호가 다릅니다.',
      tooShort: '8자 이상으로 입력해주세요.',
      updateSubmit: '비밀번호 변경',
      updated: '비밀번호를 변경했습니다. 관리자 화면으로 이동합니다.',
      backToLogin: '로그인 화면으로',
    },
    reauth: {
      title: '다시 로그인해주세요',
      body: '로그인 시간이 지나 저장하지 못했습니다. 작성 중인 내용은 이 화면에 그대로 있습니다. 다시 로그인하면 이어서 저장할 수 있습니다.',
    },
    unsavedLeave: '저장하지 않은 메모가 있습니다. 이동하면 작성한 내용이 사라집니다.',

    dashboard: {
      title: '대시보드',
      submissions: '전체 제출',
      submissionsHelp: '학부모가 보낸 상담 건수',
      courseConsults: '수업별 상담',
      courseConsultsHelp: '한 제출에 수업이 여럿이면 수업마다 따로 셉니다',
      newCount: '신규 접수',
      needsInfo: '추가 확인 필요',
      scheduled: '일정 확정',
      bySubject: '과목별 현황',
      subject: '과목',
      total: '전체',
      upcoming: '다음 연락 예정',
      upcomingEmpty: '연락 예정일이 잡힌 상담이 없습니다.',
      overdue: '지남',
      today: '오늘',
      empty: '아직 접수된 상담이 없습니다. 수업 관리에서 초대 링크를 만들어 학부모에게 보내면 접수된 상담이 이곳에 모입니다.',
      privacyWarning: '개인정보 안내가 아직 확정되지 않아 학부모가 링크를 열어도 접수할 수 없습니다.',
      privacyWarningAction: '운영 설정에서 확정하기',
    },

    list: {
      title: '응답·상담',
      search: '검색',
      searchPlaceholder: '학생·학부모 이름, 연락처, 접수 번호',
      subject: '과목',
      course: '수업',
      grade: '학교급·학년',
      status: '상담 상태',
      needsCheck: '확인 필요',
      needsCheckOnly: '확인할 항목이 있는 상담만',
      receivedFrom: '접수일 (부터)',
      receivedTo: '접수일 (까지)',
      weekday: '희망 요일',
      timeFrom: '희망 시작 시각 (부터)',
      timeTo: '희망 시작 시각 (까지)',
      all: '전체',
      reset: '필터 초기화',
      sort: '정렬',
      sortOptions: { received_desc: '최근 접수순', received_asc: '오래된 접수순', start_asc: '희망 시작일 빠른순', student: '학생 이름순' },
      exportSummary: 'CSV · 제출 요약',
      exportDetail: 'CSV · 수업별 상세',
      exporting: '내보내는 중…',
      count: (shown: number, total: number) => `${total}건 중 ${shown}건`,
      colReceived: '접수 일시',
      colPeople: '학생 / 학부모',
      colGrade: '학년',
      colSubjects: '수업',
      colStart: '희망 시작',
      colStatus: '상태',
      colUnknown: '확인할 항목',
      colPhone: '연락처',
      empty: '접수된 상담이 없습니다.',
      noMatch: '조건에 맞는 상담이 없습니다. 필터를 바꿔보세요.',
      page: (p: number, n: number) => `${n}쪽 중 ${p}쪽`,
      prev: '이전 쪽',
      next: '다음 쪽',
      startUndecided: '미정',
      startFixed: '확정일',
    },

    detail: {
      back: '목록으로',
      receipt: '접수 번호',
      received: '접수 일시',
      invitation: '초대 링크',
      parent: '학부모',
      phone: '연락처',
      student: '학생',
      school: '학교',
      generalRequest: '전반적인 요청',
      consecutive: '연속 수업 희망',
      commonExtra: '공통 질문',
      consent: '개인정보 동의',
      summary: '수업 준비 요약',
      sections: {
        goal: '1. 학습 목표',
        progress: '2. 학교 진도·교재',
        difficulty: '3. 어려워하는 부분',
        check: '4. 확인할 사항',
        schedule: '5. 일정·숙제 가능 시간',
        plan: '6. 지도 계획 메모',
      },
      noUnknowns: '모름·미정으로 남은 항목이 없습니다.',
      original: '학부모 원본 응답',
      originalHelp: '학부모가 보낸 내용 그대로입니다. 수정할 수 없습니다.',
      versionInfo: (v: number | null) => (v ? `작성 당시 양식 v${v}` : ''),
      wish: '희망',
      confirmed: '확정',
      teacherArea: '선생님 기록',
      teacherAreaHelp: '학부모 응답과 별도로 저장되며 학부모에게 보이지 않습니다.',
      status: '상담 상태',
      consultMemo: '상담 메모',
      planMemo: '지도 계획 메모',
      confirmedStart: '확정 시작일',
      confirmedMinutes: '확정 수업 길이(분)',
      confirmedSlots: '확정 요일·시각',
      nextContact: '다음 연락 예정일',
      createdAt: '기록 생성',
      updatedAt: '마지막 수정',
      saveRecord: '기록 저장',
      unsaved: '저장하지 않은 변경 사항이 있습니다.',
      conflict: '다른 화면에서 이 기록이 먼저 수정되었습니다. 작성 중인 내용은 그대로 두었습니다. ‘최신 내용 불러오기’를 누른 뒤 다시 저장해주세요.',
      reload: '최신 내용 불러오기',
      sms: '확인 문자 초안',
      deleteTitle: '응답 삭제',
      deleteHelp:
        '이 제출과 연결된 모든 수업의 응답, 상담 메모, 확정 일정이 함께 삭제되며 되돌릴 수 없습니다.',
      deleteConfirmLabel: (name: string) => `삭제하려면 학생 이름(‘${name}’)을 그대로 입력해주세요.`,
      deleteButton: '이 응답 영구 삭제',
      deleteMismatch: '학생 이름이 일치하지 않습니다.',
      deleted: '응답을 삭제했습니다.',
      notFound: '응답을 찾을 수 없습니다. 이미 삭제되었을 수 있습니다.',
    },

    sms: {
      title: '확인 문자 초안',
      help: '모름·미정으로 남은 내용을 모아 문자 초안을 만듭니다. 자동으로 보내지 않으니 내용을 고친 뒤 복사해서 직접 보내주세요.',
      chooseCourses: '포함할 수업',
      includeSchedule: '일정 안내 포함',
      draft: '문자 내용',
      copy: '복사',
      empty: '확인할 항목이 없습니다. 필요한 내용을 직접 적어주세요.',
    },

    courses: {
      title: '수업 관리',
      add: '새 수업 만들기',
      edit: '수업 수정',
      empty: '아직 만든 수업이 없습니다. ‘새 수업 만들기’로 첫 수업을 등록해주세요.',
      name: '수업 이름',
      nameHelp: '학부모 화면에 그대로 보입니다. 예: 중학교 과학 토요반',
      subject: '과목',
      template: '설문 양식',
      templateHelp: '이 수업 상담에 쓸 과목 양식입니다.',
      templateUnpublished: '발행된 버전이 없는 양식입니다. 발행해야 학부모가 작성할 수 있습니다.',
      schoolLevel: '대상 학교급',
      grades: '대상 학년',
      gradesHelp: '고르지 않으면 학년 무관으로 표시됩니다.',
      scope: '과정명 또는 지도 범위',
      mode: '수업 방식',
      groupType: '수업 형태',
      sessions: '주당 횟수',
      sessionChoices: '학부모가 고를 수 있는 주당 횟수',
      sessionChoicesHelp: '주당 횟수를 조율할 때 학부모가 고를 수 있는 값입니다. 고르지 않으면 주 1~5회 중에서 고르게 됩니다.',
      minutes: '회당 시간(분)',
      weekdays: '가능한 요일',
      weekdaysHelp: '고르지 않으면 요일은 협의로 표시됩니다.',
      timeBands: '가능한 시간대',
      startTime: '시작 시각',
      startTimeHelp: '정해진 시작 시각이 있을 때만 입력합니다.',
      endPreview: (t: string) => `종료 시각: ${t}`,
      timeNote: '시간 안내',
      timeNoteHelp: '예: 토요일 오전 중 협의',
      startDate: '시작일',
      duration: '수업 기간',
      fixed: '확정된 조건',
      fixedHelp: '체크한 조건은 학부모에게 안내만 하고 체크하지 않은 조건은 희망을 묻습니다.',
      notice: '수업 안내',
      noticeHelp: '학부모 첫 화면의 수업 요약 아래에 보입니다.',
      status: '접수 상태',
      statusLabels: { open: '접수 중', closed: '접수 마감', archived: '보관' } as Record<string, string>,
      responses: (n: number) => `응답 ${n}건`,
      save: '수업 저장',
      deleteUnused: '수업 삭제',
      deleteInUse: '응답이나 초대 링크와 연결된 수업은 삭제할 수 없습니다. 대신 보관 상태로 바꿔주세요.',
      invitations: '초대 링크',
      invitationsHelp: '링크에는 이름이나 전화번호가 들어가지 않습니다. 링크로는 새 상담만 보낼 수 있으며 이미 보낸 응답은 볼 수 없습니다.',
      newInvitation: '초대 링크 만들기',
      invitationLabel: '관리용 이름',
      invitationLabelHelp: '학부모에게는 보이지 않습니다. 예: 10월 과학 상담',
      invitationCourses: '연결할 수업',
      allowMultiple: '여러 수업 중에서 학부모가 고르게 하기',
      expiresAt: '마감 일시',
      maxSubmissions: '최대 접수 건수',
      createInvitation: '링크 만들기',
      copyLink: '링크 복사',
      deactivate: '링크 끄기',
      activate: '링크 다시 켜기',
      invitationState: {
        open: '접수 중',
        closed: '꺼짐 또는 수업 마감',
        expired: '기간 지남',
        full: '인원 마감',
        not_ready: '개인정보 안내 미확정',
        invalid: '확인 불가',
      } as Record<string, string>,
      submissions: (n: number) => `접수 ${n}건`,
      singleCourse: '수업 1개 고정',
      multiCourse: '여러 수업 선택',
    },

    forms: {
      title: '과목·설문 관리',
      subjects: '과목',
      addSubject: '새 과목 추가',
      subjectName: '과목 이름',
      subjectDescription: '간단한 소개',
      subjectPerspective: '지도 관점',
      subjectPerspectiveHelp: '학부모 화면의 과목별 학습 정보 단계 맨 위에 보입니다.',
      sortOrder: '표시 순서',
      active: '사용',
      inactive: '사용 안 함',
      archived: '보관됨',
      archive: '보관',
      unarchive: '보관 해제',
      templateSource: '처음 질문 가져오기',
      templateSourceStandard: '기본 학습 질문으로 시작',
      templateSourceCopy: (name: string) => `${name} 복사`,
      saveSubject: '과목 저장',
      deleteSubject: '과목 삭제',
      subjectInUse: '수업이나 응답과 연결된 과목은 삭제할 수 없습니다. 보관해주세요.',
      templates: '설문 양식',
      commonTemplate: '공통 질문',
      published: (v: number) => `v${v} 발행됨`,
      notPublished: '발행 전',
      draft: '초안 있음',
      editTemplate: '질문 편집',
      copyTemplate: '양식 복사',
      copyName: '새 양식 이름',
      systemFieldsTitle: '편집할 수 없는 기본 항목',
      systemFields:
        '학부모·학생 기본 정보, 수업 일정, 시험·숙제 시간, 개인정보 동의는 모든 양식에 자동으로 들어가며 여기서 바꿀 수 없습니다.',
      editor: {
        title: (name: string) => `${name} 질문 편집`,
        basedOn: (v: number | null) => (v ? `v${v}을 바탕으로 한 초안입니다.` : '아직 발행한 적 없는 초안입니다.'),
        saveDraft: '초안 저장',
        publish: '발행',
        publishConfirm: '발행하면 새 버전이 만들어지고 이후 접수되는 상담부터 적용됩니다. 이미 받은 응답은 작성 당시 버전 그대로 보존됩니다.',
        discard: '초안 버리기',
        preview: '모바일 미리보기',
        addQuestion: '질문 추가',
        moveUp: '위로',
        moveDown: '아래로',
        remove: '삭제',
        lockedHint: '기본 질문이라 삭제하거나 유형을 바꿀 수 없습니다. 문구 수정과 숨기기는 가능합니다.',
        id: '질문 ID',
        idHelp: '영문 소문자·숫자·밑줄만 씁니다. 발행한 뒤에는 바꾸지 않는 것이 좋습니다.',
        type: '유형',
        label: '질문 문구',
        help: '도움말',
        required: '필수',
        active: '사용',
        allowUnknown: '‘모름·미정’ 선택지 제공',
        unknownLabel: '모름·미정 선택지 문구',
        options: '선택지',
        optionValue: '값',
        optionLabel: '표시 문구',
        optionExclusive: '단독 선택',
        addOption: '선택지 추가',
        maxLength: '최대 글자 수',
        min: '최솟값',
        max: '최댓값',
        showIf: '표시 조건',
        showIfNone: '항상 표시',
        showIfQuestion: '이 질문의 답이',
        showIfAnyOf: '다음 중 하나일 때만 표시',
        grades: '적용 학년',
        gradesHelp: '고르지 않으면 모든 학년에 보입니다. 고르면 해당 학년 학생에게만 보입니다.',
        courses: '적용 수업',
        coursesHelp: '고르지 않으면 이 양식을 쓰는 모든 수업에 적용됩니다.',
        followup: '확인 문자 문구',
        followupHelp: '‘모름’으로 답했을 때 문자 초안에 들어갈 질문입니다.',
        role: '요약 위치',
        types: {
          short_text: '짧은 글',
          long_text: '긴 글',
          single: '단일 선택',
          multi: '복수 선택',
          number: '숫자',
          date: '날짜',
          time: '시각',
          photos: '사진 첨부',
        } as Record<string, string>,
        roles: {
          '': '기타 응답',
          goal: '학습 목표',
          textbook: '교재',
          progress: '학교 진도',
          difficulty: '어려워하는 부분',
          score: '성적',
          confidence: '흥미·자신감',
          note: '참고 사항',
          other: '기타 응답',
        } as Record<string, string>,
        defErrors: {
          bad_id: '질문 ID 형식을 확인해주세요.',
          duplicate_id: '같은 질문 ID가 이미 있습니다.',
          bad_label: '질문 문구를 입력해주세요.',
          bad_help: '도움말은 300자 이내로 적어주세요.',
          bad_options: '선택지를 1~30개 넣어주세요.',
          bad_option: '선택지 값(영문 소문자·숫자·밑줄)과 표시 문구를 확인해주세요.',
          duplicate_option: '선택지 값이 겹칩니다.',
          bad_max_length: '최대 글자 수를 확인해주세요.',
          show_if_ref: '표시 조건은 앞에 있는 선택형 질문만 기준으로 삼을 수 있습니다.',
          show_if_option: '표시 조건의 선택지를 골라주세요.',
          bad_grades: '적용 학년을 다시 골라주세요.',
        } as Record<string, string>,
        saved: '초안을 저장했습니다.',
        publishedDone: (v: number) => `v${v}을 발행했습니다.`,
        empty: '질문이 없습니다.',
        previewNote: '학부모 화면과 같은 입력 요소로 보여줍니다. 여기서 입력한 내용은 저장되지 않습니다.',
        versions: '버전 기록',
        versionResponses: (n: number) => `응답 ${n}건`,
        unsaved: '저장하지 않은 변경 사항이 있습니다.',
      },
    },

    settings: {
      title: '운영 설정',
      service: '서비스 이름과 첫 화면',
      serviceName: '서비스 이름',
      parentTitle: '학부모 화면 제목',
      teacherName: '선생님 이름',
      teacherNameHelp: '입력하면 학부모 화면 머리말에 ‘○○○ 선생님 | 학습 상담’으로 표시됩니다. 비워두면 ‘학습 상담’만 보입니다.',
      teacherIntro: '선생님 소개',
      teacherIntroHelp: '사실만 적어주세요. 비워두면 표시하지 않습니다.',
      introEyebrow: '작은 안내',
      introTitle: '첫 화면 제목',
      introBody: '첫 화면 설명',
      introNote: '보조 안내',
      completion: '접수 완료 문구',
      policyNotice: '수업료·환불·취소 안내',
      policyNoticeHelp: '학부모 첫 화면과 검토 화면에 그대로 보입니다. 실제로 적용하는 규정만 적어주세요.',
      privacy: '개인정보 안내',
      privacyHelp: '학부모가 동의하기 전에 보는 안내입니다. 실제 운영 내용으로 채운 뒤 ‘확정’해야 접수가 열립니다.',
      operatorName: '운영자 이름',
      operatorContact: '운영자 연락처',
      privacyPurpose: '이용 목적',
      privacyRetention: '보관 기간',
      privacyRetentionHelp: '예: 수업 종료 후 6개월, 또는 상담만 하고 수업하지 않으면 상담 후 3개월',
      privacyDeletion: '삭제 요청 방법',
      privacyDeletionHelp: '예: 운영자 연락처로 문자를 보내주시면 확인 후 삭제하고 결과를 알려드립니다.',
      privacyConfirmed: '위 내용을 확인했고 공개 접수에 사용합니다.',
      privacyConfirmedAt: (t: string) => `확정 일시: ${t}`,
      privacyIncomplete: '운영자 이름, 연락처, 이용 목적, 보관 기간, 삭제 요청 방법을 모두 입력해야 확정할 수 있습니다.',
      save: '설정 저장',
      notice: '법적 요건 충족 여부는 이 화면이 판단하지 않습니다. 필요하면 관련 안내를 직접 확인해주세요.',
    },
  },
} as const;

export function schoolGradeLabel(level: string, grade: number | null, note?: string): string {
  if (level === 'other') return note ? `기타 (${note})` : '기타';
  const short = T.labels.schoolShort[level];
  return short && grade ? `${short}${grade}` : T.labels.schoolLevel[level] ?? '';
}
